version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:nightly # Change to "latest" for stable
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/carly/homelab/arr_stack/prowlarr/config:/config
      - /home/carly/homelab/arr_stack/prowlarr/backup:/data/Backup
      - /mnt/4TB/Downloads:/data/downloads
    ports:
      - 9697:9696
    restart: unless-stopped
    networks:
      - arrs

  sonarr:
    image: lscr.io/linuxserver/sonarr:develop # Change to "latest" for stable
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/carly/homelab/arr_stack/sonarr/config:/config
      - /home/carly/homelab/arr_stack/sonarr/backup:/data/Backup
      - /mnt/4TB/Downloads/tv-sonarr:/data/sonarr  # <== add root downloads folder here
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arrs

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/carly/homelab/arr_stack/radarr/config:/config
      - /home/carly/homelab/arr_stack/radarr/backup:/data/Backup
      - /mnt/4TB/Downloads/radarr:/data/radarr   # <== add root downloads folder here
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - arrs


  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Pacific/Auckland
    ports:
      - "8191:8191"
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - /home/carly/homelab/jackett/config:/config
      - /mnt/4TB/Downloads/jackett/downloads:/downloads
    restart: unless-stopped

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - BASE_URL=/ #optional
    volumes:
      - /home/carly/homelab/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped


networks:
  arrs:
    driver: bridge
    ipam:
      config:
        - subnet: 173.25.0.0/16
          gateway: 173.25.0.1
